#!/usr/bin/env python
"""
streamlit_app.py

Streamlit dashboard for the DSC 670 Term Project.

- Loads the latest watchlist_with_llm_YYYYMMDD.csv generated by
  build_watchlist_with_llm.py
- Displays a sortable, filterable main table
- Provides sidebar filters (stance, decision, score ranges, text search)
- Optional "Refresh" button to re-run the full pipeline with the fine-tuned model
"""

from pathlib import Path
from typing import Optional

import numpy as np
import pandas as pd
import streamlit as st
import altair as alt

from build_watchlist_with_llm import run_pipeline

# ---------------------------------------------------------------------
# Streamlit page config
# ---------------------------------------------------------------------

st.set_page_config(
    page_title="Stock Stance Dashboard",
    page_icon="📈",
    layout="wide",
)

# ---------------------------------------------------------------------
# Helpers to find and load the latest CSV
# ---------------------------------------------------------------------

def find_latest_llm_csv(
    prefix: str = "watchlist_with_llm_",
    suffix: str = ".csv",
    search_dir: str | Path = ".",
) -> Optional[Path]:
    """
    Look for files like watchlist_with_llm_YYYYMMDD.csv
    in the given directory and return the one with the latest mtime.
    """
    search_dir = Path(search_dir)
    files = list(search_dir.glob(f"{prefix}*{suffix}"))
    if not files:
        return None
    # Sort by modification time, newest first
    files.sort(key=lambda p: p.stat().st_mtime, reverse=True)
    return files[0]


@st.cache_data
def load_csv(path: Path) -> pd.DataFrame:
    """
    Cached CSV loader. Clears automatically when the path changes.
    """
    return pd.read_csv(path)


# ---------------------------------------------------------------------
# Filtering logic
# ---------------------------------------------------------------------

def apply_quick_filters(df: pd.DataFrame) -> pd.DataFrame:
    """
    Quick, high-level filters in the sidebar: Name, symbol, stance, decision, score ranges.
    """
    filtered = df.copy()

    st.sidebar.header("Quick filters")

    # Name text filter
    if "Name" in filtered.columns:
        name_query = st.sidebar.text_input("Name contains", value="")
        if name_query:
            filtered = filtered[
                filtered["Name"].astype(str).str.contains(name_query, case=False, na=False)
            ]

    # Symbol text filter
    if "symbol" in filtered.columns:
        sym_query = st.sidebar.text_input("Symbol contains", value="")
        if sym_query:
            filtered = filtered[
                filtered["symbol"].astype(str).str.contains(sym_query, case=False, na=False)
            ]

    # LLM stance filter
    if "llm_stance" in filtered.columns:
        stance_vals = sorted(filtered["llm_stance"].dropna().unique().tolist())
        if stance_vals:
            stance_selected = st.sidebar.multiselect(
                "LLM stance",
                options=stance_vals,
                default=stance_vals,
            )
            if stance_selected:
                filtered = filtered[filtered["llm_stance"].isin(stance_selected)]

    # Final decision filter
    if "final_decision" in filtered.columns:
        decision_vals = sorted(filtered["final_decision"].dropna().unique().tolist())
        if decision_vals:
            decision_selected = st.sidebar.multiselect(
                "Final decision",
                options=decision_vals,
                default=decision_vals,
            )
            if decision_selected:
                filtered = filtered[filtered["final_decision"].isin(decision_selected)]

    # Score range filters
    def numeric_range_filter(col_name: str, label: str):
        nonlocal filtered
        if col_name in filtered.columns:
            col = filtered[col_name]
            col = pd.to_numeric(col, errors="coerce")
            if col.notna().any():
                min_val = float(col.min())
                max_val = float(col.max())
                if min_val == max_val:
                    return
                user_min, user_max = st.sidebar.slider(
                    label,
                    min_value=min_val,
                    max_value=max_val,
                    value=(min_val, max_val),
                )
                filtered = filtered[
                    col.between(user_min, user_max, inclusive="both")
                ]

    numeric_range_filter("local_score", "Local score range")
    numeric_range_filter("llm_score", "LLM score range")
    numeric_range_filter("final_score", "Final score range")

    return filtered


def apply_advanced_filters(df: pd.DataFrame) -> pd.DataFrame:
    """
    Optional advanced filters in a sidebar expander:
    - For numeric columns: range sliders
    - For low-cardinality categorical/string columns: multiselects

    This makes "every column filterable," more Excel-like.
    """
    filtered = df.copy()

    with st.sidebar.expander("Advanced column filters (optional)", expanded=False):
        st.write(
            "Use these only if user want fine-grained filtering. "
            "Quick filters above might be enough for most use cases."
        )

        for col in filtered.columns:
            series = filtered[col]

            # Skip if all values are NaN
            if series.dropna().empty:
                continue

            # Numeric columns: range slider
            if pd.api.types.is_numeric_dtype(series):
                col_min = float(series.min())
                col_max = float(series.max())
                if col_min == col_max:
                    continue  # single-valued, no need for range filter

                user_min, user_max = st.slider(
                    f"{col} range",
                    min_value=col_min,
                    max_value=col_max,
                    value=(col_min, col_max),
                )
                filtered = filtered[
                    series.between(user_min, user_max, inclusive="both")
                ]

            else:
                # Treat as categorical/string column
                # Only make a multiselect if cardinality is reasonable
                unique_vals = series.dropna().unique().tolist()
                if 0 < len(unique_vals) <= 50:
                    # Default: select all
                    selected_vals = st.multiselect(
                        f"{col} values",
                        options=sorted(map(str, unique_vals)),
                        default=sorted(map(str, unique_vals)),
                    )
                    if selected_vals:
                        filtered = filtered[
                            series.astype(str).isin(selected_vals)
                        ]

    return filtered


# ---------------------------------------------------------------------
# Main app
# ---------------------------------------------------------------------

def main():
    st.title("📈 Stock Stance Dashboard")
    st.caption(
        "Powered by engineered technical indicators + a fine-tuned OpenAI stance model."
    )

    # --- Sidebar: Refresh button ---
    st.sidebar.markdown("### Data refresh")

    if st.sidebar.button("🔄 Refresh data (re-run model)", use_container_width=True):
        with st.spinner("Running pipeline with fine-tuned model..."):
            # Run the pipeline; this will generate a new CSV and return a fresh DataFrame
            run_pipeline(
                watchlist_csv="Chance_Watchlist.csv",
                ticker_col="Symbol",
                with_llm=True,
                inference_config="m3_artifacts/inference_config.json",
                max_llm_rows=None,  # set to int for faster testing, None for all
                out_csv=None,        # let the function auto-name the CSV
            )
        # Clear cached CSV loader so next call sees the updated file
        load_csv.clear()
        st.success("Data refreshed using the fine-tuned model!")

    # --- Load latest CSV ---
    latest_path = find_latest_llm_csv()
    if latest_path is None:
        st.error(
            "No watchlist_with_llm_*.csv files found.\n\n"
            "Run `build_watchlist_with_llm.py --with-llm` at least once, "
            "or use the 'Refresh data' button in the sidebar."
        )
        return

    st.info(f"Using data from: `{latest_path.name}`")

    df = load_csv(latest_path)

    if df.empty:
        st.warning("Loaded CSV is empty; nothing to display.")
        return

    # --- Apply filters ---
    filtered_df = apply_quick_filters(df)
    filtered_df = apply_advanced_filters(filtered_df)

    # --- Summary metrics ---
    st.subheader("Summary")

    col1, col2, col3 = st.columns(3)
    col1.metric("Tickers (after filters)", f"{len(filtered_df):,}")

    if "final_decision" in filtered_df.columns:
        decision_counts = filtered_df["final_decision"].value_counts()
        top_decision = decision_counts.idxmax()
        top_count = decision_counts.max()
        col2.metric("Most common decision", f"{top_decision} ({top_count})")

    if "final_score" in filtered_df.columns and filtered_df["final_score"].notna().any():
        avg_score = filtered_df["final_score"].mean()
        col3.metric("Average final score", f"{avg_score:.2f}")

     # Optional: show decision distribution chart with horizontal labels
    if "final_decision" in filtered_df.columns:
        st.markdown("#### Final decision distribution")

        decision_counts = (
            filtered_df["final_decision"]
            .value_counts()
            .reset_index(name="count")          # counts go into 'count'
            .rename(columns={"index": "final_decision"})  # index -> 'final_decision'
        )

        chart = (
            alt.Chart(decision_counts)
            .mark_bar()
            .encode(
                x=alt.X(
                    "final_decision:N",
                    title="Final decision",
                    sort=None,
                    axis=alt.Axis(labelAngle=0),  # keep text horizontal
                ),
                y=alt.Y("count:Q", title="Count"),
                tooltip=["final_decision:N", "count:Q"],
            )
        )

        st.altair_chart(chart, use_container_width=True)


    st.markdown("---")

    # --- Main table ---
    st.subheader("Watchlist details")

    st.caption(
        "Table is sortable by any column. Use the sidebar for filters. "
        "Scroll horizontally to see all metrics."
    )

    # Ensure Name, symbol, date are first if present; respect CSV order otherwise
    preferred_front = [c for c in ["Name", "symbol", "date"] if c in filtered_df.columns]
    other_cols = [c for c in filtered_df.columns if c not in preferred_front]
    table_df = filtered_df[preferred_front + other_cols]

    # Show as interactive table; Streamlit UI supports sorting by clicking headers
    st.dataframe(
        table_df,
        use_container_width=True,
        hide_index=True,
    )

    # --- Optional per-ticker detail panel ---
    if "symbol" in table_df.columns:
        st.markdown("---")
        st.subheader("Per-ticker detail")

        symbols = table_df["symbol"].dropna().unique().tolist()
        default_symbol = symbols[0] if symbols else None

        selected_symbol = st.selectbox(
            "Select a symbol to inspect",
            options=symbols,
            index=0 if default_symbol is not None else None,
        )

        if selected_symbol is not None:
            detail_rows = table_df[table_df["symbol"] == selected_symbol]
            st.write(f"Showing {len(detail_rows)} row(s) for **{selected_symbol}**")

            # Show metrics for the selected symbol
            st.dataframe(
                detail_rows,
                use_container_width=True,
                hide_index=True,
            )

            # If we have an LLM summary, surface it clearly
            if "llm_summary" in detail_rows.columns:
                st.markdown("##### LLM Summary")
                for _, r in detail_rows.iterrows():
                    if pd.notna(r.get("llm_summary", None)):
                        st.write(f"- {r['llm_summary']}")
                        break  # show the first non-null summary

# ---------------------------------------------------------------------

if __name__ == "__main__":
    main()
